logo: assets/img/profilepic.png
second_logo: assets/img/BO-Logo.png
title: Chas Riley
description: Cybersecurity Professional
linkedin_url: https://www.linkedin.com/in/chas-riley/

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
include:
  - assets/css/custom.css

